name: CI
on:
  workflow_dispatch:
  push:
    branches: [ baseline, demo-start, migrated ]
  pull_request:
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm ci
      - run: npm run build
      - run: npm run test -- --watch=false --code-coverage --browsers=ChromeHeadless
